meta_product_name: "Chum"
meta_title: "Chum – Choose How U Meet People for your next vacation"
meta_description: "Meet new friends for your next vacation"
meta_image: "logo.png" # should exist in `app/assets/images/`
